### ISSUE TITLE
exporting the TD in GraphML

### ISSUE THREAD

**Issue by SofianeTanji** [bbliem/dflat#14]
Hi,

Currently, when exporting a tree decomposition in the GraphML format using "--graphml-out", the resulting file can't be imported with networkX (Python library for graphs) because of an attribute missing.
This line : `
<key id="bag" for="node"/>`
needs to be modified this way :`
<key attr.name="bag" attr.type="string" for="node" id="bag"/>`

Otherwise, networkX will raise an "unknown id 'bag' " error because of attr.name being None.

**Comment by bbliem** [comment]
Hi, Thanks for the suggestion, I added this.
